/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#aeecff",
        "tertiary-fixed": "#cbe6ff",
        "secondary-fixed-dim": "#00d9ff",
        "primary-container": "#0074da",
        "surface-variant": "#d1e4ff",
        "on-tertiary-fixed-variant": "#004b71",
        "on-background": "#011d35",
        "inverse-surface": "#19324b",
        "on-secondary-container": "#005b6c",
        "background": "#f8f9ff",
        "inverse-primary": "#a7c8ff",
        "surface-container-low": "#eef4ff",
        "secondary-container": "#00d9ff",
        "surface-container-highest": "#d1e4ff",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fefcff",
        "error": "#ba1a1a",
        "tertiary": "#006191",
        "on-surface-variant": "#404754",
        "on-primary-fixed-variant": "#004788",
        "secondary": "#00687b",
        "error-container": "#ffdad6",
        "surface-container-high": "#dbe9ff",
        "surface-dim": "#c4dcfd",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#001f26",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#fcfcff",
        "on-secondary-fixed-variant": "#004e5d",
        "surface-container": "#e4efff",
        "on-primary": "#ffffff",
        "primary-fixed": "#d5e3ff",
        "on-error-container": "#93000a",
        "primary": "#005cae",
        "on-tertiary-fixed": "#001e30",
        "tertiary-fixed-dim": "#8fcdff",
        "outline-variant": "#c0c6d6",
        "inverse-on-surface": "#e9f1ff",
        "primary-fixed-dim": "#a7c8ff",
        "outline": "#717785",
        "tertiary-container": "#007bb6",
        "on-primary-fixed": "#001b3c",
        "on-error": "#ffffff",
        "surface": "#f8f9ff",
        "on-surface": "#011d35",
        "surface-tint": "#005eb2",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
      spacing: {
        "3xl": "4rem",
        "5xl": "8rem",
        "gutter-desktop": "2rem",
        "sm": "0.75rem",
        "gutter-mobile": "1rem",
        "4xl": "6rem",
        "md": "1rem",
        "xs": "0.5rem",
        "2xs": "0.25rem",
        "2xl": "3rem",
        "xl": "2rem",
        "container-max": "80rem",
        "lg": "1.5rem",
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "display-hero-mobile": ["Space Grotesk", "sans-serif"],
        "label-lg": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Space Grotesk", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "display-hero": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "54px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-hero-mobile": ["44px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-hero": ["80px", { lineHeight: "88px", letterSpacing: "-0.04em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
